### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by LowderPlay** [aholachek/react-flip-toolkit#224]
Hi! Thanks for the amazing package!

When using the 7.2.0 version, TypeScript complains about type declarations:
```
error TS7016: Could not find a declaration file for module 'react-flip-toolkit'. '<..>/react-flip-toolkit/lib/index.modern.mjs' implicitly has an 'any' type.
  There are types at '<..>/react-flip-toolkit/lib/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'react-flip-toolkit' library may need to update its package.json or typings.
```

The error isn't there on the 7.1.0 version, as the issue was introduced in the commit cc171422c26130ef5c00cd667033700b95d1e70f.

**Comment by aholachek** [comment]
@LowderPlay thanks so much for flagging this 🙇 . I've published [a new version](https://github.com/aholachek/react-flip-toolkit/releases/tag/v7.2.4)that should fix the issue for now.
